project:
  type: website

website:
  title: "DATS 4001 Capstone"
  navbar:
    background: primary
    search: true
    left:
      - href: index.qmd
        text: Home
      - href: Project.qmd
        text: Project
      

format:
  html:
    theme: darkly
    css: styles.css
    toc: true

editor: visual

