```{r setup, include=FALSE, echo=FALSE, message=FALSE, warning=FALSE, include=FALSE}

#install.packages("")

library(tidyverse)
library(tidycensus)
library(tigris)
library(sf) 
library(tmap)
library(dplyr)
library(ggthemes)
library(RColorBrewer)
library(plotly)
library(readxl)
library(huxtable)
library(table1)
library(kableExtra)
library(readxl)

```

## The Background

```{r, echo=FALSE, message=FALSE, warning=FALSE, include = FALSE}

census_api_key("c9264540e1e33a3c55dacba891cde5dd6a5ebb5e", overwrite = TRUE)

tmap_mode("view")

#v = load_variables(2022, "acs1", cache = TRUE)
#View(v)

#B05010_002 - total ratio for income to poverty level, children under 18
#B05010_003 - two parents
#B05010_004 - two parents native
#B05010_005 - two parents foreign born
#B05010_006 - one native one foreign born parents
#B05010_007 - one parent
#B05010_008 - one parent native
#B05010_009 - one parent foreign born

my_variables1 = c(
  twoparentsn = "B05010_004",
  twoparentsf = "B05010_005"
)

d_acs = get_acs(
  geography = "county",
  variables = my_variables1, 
  state = "MA",
  year = 2022,
  survey = "acs1",
  geometry = TRUE,
  resolution = "20m")

map1 = tm_shape(d_acs, projection="+proj=eck4") + 
  tm_polygons("estimate",
              n = 6,
              id = "NAME",
              palette = "Blues",
              title = "ACS Estimate",
              legend.hist = TRUE,
              alpha = 0.7, 
              breaks = c(0, 40000, 120000, 200000, 350000, 600000, 1000000, 1500000)) + 
  tm_borders(lwd = .50, 
             col = "black",
             alpha = 1) +
  tm_layout(inner.margins=c(0,0,.1,0), 
            title.size=.8,
            title = "Poverty Level Amongst Children under 18, Native vs Foriegn born",
            frame = TRUE,
            legend.outside = TRUE,
            legend.hist.width = 5,
            fontfamily = "Helvetica") 

```

```{r, fig.height=7, fig.width=10, fig.align="center", echo=FALSE, message=FALSE, warning=FALSE}

map1 + tm_view(set.view = c(-105, 48, 3))


```

```{r, echo=FALSE, message=FALSE, warning=FALSE, include = FALSE}

census_api_key("c9264540e1e33a3c55dacba891cde5dd6a5ebb5e", overwrite = TRUE)

tmap_mode("view")

#v = load_variables(2022, "acs1", cache = TRUE)
#View(v)

# B11012_003 = Married-couple household, With children of the householder under 18 years
# B11012_010 = Female householder, With children of the householder under 18 years
#	B11012_015 = Male householder, With children of the householder under 18 years
# B11017_001 = multi-generational households, total

# B17010B_004 = Poverty Status in the Past 12 Months Married-couple family With related children under 18                  years (Black or African American Alone Householder)
# B17010A_024 = Poverty Status in the Past 12 Months Married-couple family With related children under 18                  years (white)
# B17010C_024 = Poverty Status in the Past 12 Months Married-couple family With related children under 18                  years (Native American)
# B17010D_024 = Poverty Status in the Past 12 Months Married-couple family With related children under 18                  years (Asian)
# B17010G_024 = Poverty Status in the Past 12 Months Married-couple family With related children under 18                  years (two or more races)
# B17010I_004 = Poverty Status in the Past 12 Months Married-couple family With related children under 18                  years (hispanic)


my_variables2 = c(
  households = "B11012_003"
  )

d_acs = get_acs(
  geography = "county",
  variables = my_variables2, 
  state = "MA",
  year = 2022,
  survey = "acs1",
  geometry = TRUE,
  resolution = "20m")

map2 = tm_shape(d_acs, projection="+proj=eck4") + 
  tm_polygons("estimate",
              n = 6,
              id = "NAME",
              palette = "Blues",
              title = "ACS Estimate",
              legend.hist = TRUE,
              alpha = 0.7, 
              breaks = c(0, 40000, 120000, 200000, 350000, 600000, 1000000, 1500000)) + 
  tm_borders(lwd = .50, 
             col = "black",
             alpha = 1) +
  tm_layout(inner.margins=c(0,0,.1,0), 
            title.size=.8,
            title = "Households with Children Under 18",
            frame = TRUE,
            legend.outside = TRUE,
            legend.hist.width = 5,
            fontfamily = "Helvetica") 

```

```{r, fig.height=7, fig.width=10, fig.align="center", echo=FALSE, message=FALSE, warning=FALSE}

map2 + tm_view(set.view = c(-105, 48, 3))

```

```{r, echo=FALSE, message=FALSE, warning=FALSE, include = FALSE}

census_api_key("c9264540e1e33a3c55dacba891cde5dd6a5ebb5e", overwrite = TRUE)

tmap_mode("view")

# B25012_011 = Renter-occupied housing units With related children of the householder under 18:

# B19001A_001 = Household Income in the Past 12 Months (in 2022 Inflation-Adjusted Dollars) (White)
# B19001B_001 = Household Income in the Past 12 Months (in 2022 Inflation-Adjusted Dollars) (Black)
# B19001C_001 = native
# B19001D_001 = asian 
# B19001I_001 = hispanic
# B19001_001 = average

my_variables3 = c(
  income_white = "B19001B_001",
  income_black = "B19001A_001"
  )

d_acs = get_acs(
  geography = "county",
  variables = my_variables1, 
  state = "MA",
  year = 2022,
  survey = "acs1",
  geometry = TRUE,
  resolution = "20m")

map3 = tm_shape(d_acs, projection="+proj=eck4") + 
  tm_polygons("estimate",
              n = 6,
              id = "NAME",
              palette = "Blues",
              title = "ACS Estimate",
              legend.hist = TRUE,
              alpha = 0.7, 
              breaks = c(0, 40000, 120000, 200000, 350000, 600000, 1000000, 1500000)) + 
  tm_borders(lwd = .50, 
             col = "black",
             alpha = 1) +
  tm_layout(inner.margins=c(0,0,.1,0), 
            title.size=.8,
            title = "Household Income of Black vs White families in MA",
            frame = TRUE,
            legend.outside = TRUE,
            legend.hist.width = 5,
            fontfamily = "Helvetica") 

```

```{r, fig.height=7, fig.width=10, fig.align="center", echo=FALSE, message=FALSE, warning=FALSE}


map3 + tm_view(set.view = c(-105, 48, 3))

```

```{r}

# B17018_005 = Income in the past 12 months below poverty level, Married-couple family, High school                       graduate (includes equivalency)
# B17018_006 = Income in the past 12 months below poverty level, Married-couple family, Some college,                      associate's degree
# B17018_007 = Income in the past 12 months below poverty level, Married-couple family, Bachelor's degree                 or higher

# B17019_004 = Income in the past 12 months below poverty level, Married-couple family, Owner occupied
# B17019_005 = Income in the past 12 months below poverty level, Married-couple family, Renter occupied

```

```{r}

d_enrollment = read_excel("enrollmentbyracegender.xlsx")

colnames(d_enrollment) = as.character(d_enrollment[1,])

d_enrollment = d_enrollment[-1,]

d_enrollment = d_enrollment %>%
  rename("district_name" = "District Name",
         "district_code" = "District Code", 
         "Black" = "African American",
         "Native_American" = "Native American",
         "Pacific_Islander" = "Native Hawaiian, Pacific Islander",
         "Multi_Race" = "Multi-Race, Non-Hispanic",
         "Non_Binary" = "Non-Binary")

d_enrollment = mutate(d_enrollment, Black = as.numeric(Black),
                        Asian = as.numeric(Asian),
                        Hispanic = as.numeric(Hispanic),
                        White = as.numeric(White),
                        Native_American = as.numeric(Native_American),
                        Pacific_Islander = as.numeric(Pacific_Islander),
                        Multi_Race = as.numeric(Multi_Race), 
                        Males = as.numeric(Males),
                        Females = as.numeric(Females),
                        Non_Binary = as.numeric(Non_Binary))

plot1 = plot(d_enrollment$White)
plot1
                        
plot2 = plot(d_enrollment$Black)
plot2                     
```
